Fix missing test output when running test.py --no-r8lib
Old output:

> Task :tests_java_8:test

PartialShrinkingPreviewApiTest > [none] > testExternal[none] FAILED
    java.lang.AssertionError at BinaryCompatibilityTestCollection.java:130

3 tests completed, 1 failed



New output:

> Task :tests_java_8:test
java.lang.AssertionError: EXIT CODE: 1 STDOUT:

STDERR: Error: Could not find or load main class
org.junit.runner.JUnitCore Caused by: java.lang.ClassNotFoundException:
org.junit.runner.JUnitCore

expected:<0> but was:<1>
        at com.android.tools.r8.compilerapi.BinaryCompatibilityTestCollection.runJunitOnTestClasses(BinaryCompatibilityTestCollection.java:130)
        at com.android.tools.r8.compilerapi.BinaryCompatibilityTestCollection.runJunitOnTestClass(BinaryCompatibilityTestCollection.java:93)
        at com.android.tools.r8.compilerapi.CompilerApiTestRunner.testExternal(CompilerApiTestRunner.java:37)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)

PartialShrinkingPreviewApiTest > [none] > testExternal[none] FAILED
    java.lang.AssertionError at BinaryCompatibilityTestCollection.java:130

3 tests completed, 1 failed

Bug: b/488917294
Change-Id: Iced15a7c4932e988a8c9194f1341ea3cc3e0774d