Fix fmt-diff.py
This fixes the following error, which recently started happening, probably due to a change in depot_tools.

OSError: [Errno 8] Exec format error: 'r8/third_party/google/google-java-format/1.24.0/google-java-format-1.24.0-all-deps.jar'

Change-Id: If0850001508065f152e36c8a5abc813ec2a56be6